apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: argo-repo-creds
  namespace: argo
spec:
  suspend: false
  secretTemplates:
    - name: my-secret-name-1
      labels:
        label1: value1
      annotations:
        key1: value1
      stringData:
        data-name0: data-value0
      data:
        data-name1: ZGF0YS12YWx1ZTE=