name: Build and Push
on:
  push:
    branches:
      - main
jobs:
  buildPush:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set Up Go
        uses: actions/setup-go@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: rallinator7
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: cd app && ls
      - name: Run Mage
        uses: magefile/mage-action@v1
        with:
          args: ci
          workdir: ./app